## YAML Template.
# Spring properties
spring:
  application:
    name: video
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
  profiles:
    active: native 
    
 #Info Component.
info:
  component: video

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port

#SecretKey Token
authapp:
  secretkey: QWE*123456789*qaz123*
  
##Spring DataSource Postgres
#spring.datasource.platform: postgres 
#spring.datasource.url: jdbc:postgresql://ec2-54-197-232-155.compute-1.amazonaws.com:5432/dkrtcijgn0atm
#spring.datasource.username: auzpcqkdfhxrix
#spring.datasource.password: 0f8c7596f31b725d4cdf714b5e0c034472ad196e795da3c8696c0ea5b10fc0be
#spring.datasource.driver-class-name: org.postgresql.Driver


spring.datasource.platform: postgres 
spring.datasource.url: jdbc:postgresql://ec2-54-197-232-155.compute-1.amazonaws.com:5432/dfqks935t4qp6g
spring.datasource.username: dezvhfswhtyqvn
spring.datasource.password: 19b6c722a0a7cee129a66d2593e0f2cbc16287ca75c8a381b8f4cc6d09af572a
spring.datasource.driver-class-name: org.postgresql.Driver

#spring.datasource.url : jdbc:mysql://localhost:3306/video-capitol
#spring.datasource.username : root
#spring.datasource.password : 
#spring.datasource.driver-class-name : com.mysql.jdbc.Driver
#spring.datasource.test-on-borrow : true
#spring.datasource.validation-query : SELECT 1

# ==========================================================================
# = JPA / HIBERNATE
# ==========================================================================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database: POSTGRESQL
#spring.jpa.database: MYSQL
# Naming strategy
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
# Allows Hibernate to generate SQL optimized for a particular DBMS for MySQL:MySQL5Dialect - SQLserver:SQLServerDialect - PostgreSQLDialect - MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect.temp.use_jdbc_metadata_defaults: false
      
