## YAML Template.
# Spring properties
spring:
  application:
    name: video
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
  profiles:
    active: native 
    
 #Info Component.
info:
  component: video

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port

#SecretKey Token
authapp:
  secretkey: QWE*123456789*qaz123*
  
##Spring DataSource Postgres
#spring.datasource.platform: postgres 
#spring.datasource.url: jdbc:postgresql://localhost:5432/video-capitol
#spring.datasource.username: postgres
#spring.datasource.password: root
#spring.datasource.driver-class-name: org.postgresql.Driver

spring.datasource.url : jdbc:mysql://localhost:3306/video-capitol
spring.datasource.username : root
spring.datasource.password : 
spring.datasource.driver-class-name : com.mysql.jdbc.Driver
spring.datasource.test-on-borrow : true
spring.datasource.validation-query : SELECT 1

# ==========================================================================
# = JPA / HIBERNATE
# ==========================================================================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
#spring.jpa.database: POSTGRESQL
spring.jpa.database: MYSQL
# Naming strategy
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
# Allows Hibernate to generate SQL optimized for a particular DBMS for MySQL:MySQL5Dialect - SQLserver:SQLServerDialect - PostgreSQLDialect - MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect.temp.use_jdbc_metadata_defaults: false
      
